import { VoyoComponent, VoyoEventEmitter, VoyoTemplateRef } from "../commonComponent";
import { ClassManage, ScrollListenerEvent } from "../../utils";
import { RefreshAnimation } from "./refresh-animation";
import { Observable, Subject } from "rxjs";
import { ExcuteAfterConnected } from "../utils";
export declare class RefeshComponent extends VoyoComponent {
    defaultEffects: any;
    vibrate: boolean;
    maxDistance: number;
    triggerDistance: number;
    disabledScroll: boolean;
    refresherRefresh: VoyoEventEmitter<() => void>;
    refreshEnd: VoyoEventEmitter<any>;
    containerManage: ClassManage;
    containerEl: HTMLElement;
    runningEl: HTMLElement;
    willEl: HTMLElement;
    downEl: HTMLElement;
    articleEl: HTMLElement;
    refreshAnimation: RefreshAnimation;
    scrollContainer: HTMLElement;
    scrollContainerTop: number;
    refreshRunning: boolean;
    moveStartY: number | undefined;
    refreshTriggerSubject: Subject<boolean>;
    executeAfterConnected: ExcuteAfterConnected;
    listenScroll: Observable<ScrollListenerEvent>;
    pauseRefresh(): void;
    _canMove: boolean;
    disableTouchStart: boolean;
    downTemplate: VoyoTemplateRef;
    runningTemplate: VoyoTemplateRef;
    willTemplate: VoyoTemplateRef;
    get disableTouch(): boolean;
    get disableEndTouch(): boolean;
    get canMove(): boolean;
    parentScrollBePrevented: boolean;
    preventParentScroll(): void;
    restoreParentScroll(): void;
    refreshTrigger(): void;
    refreshTriggerEnd(): void;
    refresherEnd(): void;
    created(): void;
    handlerRefreshContainer(): void;
    handlerSlot(): void;
    mounted(): void;
}
